CREATE TABLE store (
    id BIGINT NOT NULL COMMENT '门店ID',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    organization_id BIGINT NOT NULL COMMENT '归属组织单元ID',
    store_code VARCHAR(64) NOT NULL COMMENT '门店编码',
    store_name VARCHAR(128) NOT NULL COMMENT '门店名称',
    business_format VARCHAR(64) NULL COMMENT '经营业态',
    operation_status VARCHAR(32) NOT NULL COMMENT '营业状态',
    country_code VARCHAR(8) NOT NULL DEFAULT 'CN' COMMENT '国家或地区编码',
    province VARCHAR(64) NULL COMMENT '省份',
    city VARCHAR(64) NULL COMMENT '城市',
    district VARCHAR(64) NULL COMMENT '区县',
    address VARCHAR(255) NULL COMMENT '详细地址',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '门店时区',
    opened_on DATE NULL COMMENT '开业日期',
    closed_on DATE NULL COMMENT '停业日期',
    created_by BIGINT NULL COMMENT '创建人',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_by BIGINT NULL COMMENT '更新人',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    PRIMARY KEY (id),
    UNIQUE KEY uk_store_tenant_code (tenant_id, store_code),
    KEY idx_store_tenant_organization (tenant_id, organization_id),
    KEY idx_store_tenant_status (tenant_id, operation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='经营门店';
